### ISSUE TITLE
Reentrancy anomaly was detected

### ISSUE THREAD

**Issue by croccio** [RxSwiftCommunity/RxBiBinding#20]
I'm using it with BehaviorRelay<->BehaviorRelay 

Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/antonioscardigno/Documents/Sogetel/repository-forward/SOGETEL-RUMORS/DEV/iOSProjects/branches/newUI/Pods/RxSwift/RxSwift/Rx.swift:97 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueing sequence events in some other way.

**Comment by Davarg** [comment]
@croccio Hello, thank you for issue. I'll deal with it soon.
