### ISSUE TITLE
CocoaPods could not find compatible versions for pod "RxBiBinding"

### ISSUE THREAD

**Issue by luucassoares** [RxSwiftCommunity/RxBiBinding#21]
Hello guys, good morning.

Recently I needed to do the two way data binding with RxSwift and searching in the github community, I've found this pod.. 

But when I run pod install I face this issue: 
Specs satisfying the `RxBiBinding` dependency were found, but they required a higher minimum deployment target.

Can anyone help me?
The minimum iOS version for my app is 11.0 so and in the readme it says that this pod requires at least ios 10.
Anyone faced this problem before?

Thanks in advance!

best regards

**Comment by Davarg** [comment]
Hmm, very strange. I will checkout this issue at the weekend.

**Comment by luucassoares** [comment]
Ok, thanks a lot! Will wait for your feedback!

**Comment by luucassoares** [comment]
> Hmm, very strange. I will checkout this issue at the weekend.
> 
> @luucassoares maybe you have extension, for example, for WatchOS with different deployment target. And check deployment target of RxSwift, RxCocoa in Pods project, by default it setted to 6 iOS

Ohhh in fact that was it. platform :ios, '10.0' was setted to 9.0 on my podfile. setting it to 10.0 solved my issue! thank you a lot! I will close this issue..hope you have a good day
