### ISSUE TITLE
UISwitch

### ISSUE THREAD

**Issue by Anavrin1990** [RxSwiftCommunity/RxBiBinding#22]
UISwitch skip first value when toggle

    @IBOutlet weak var testSwitch: UISwitch!
    
    let isOn = BehaviorRelay<Bool>(value: true)
    
    let db = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        (testSwitch.rx.isOn <-> isOn).disposed(by: db)        
        
        isOn.subscribe(onNext: { (value) in
            print(value)
        }).disposed(by: db)
    }

But if add another property and bind after UISwitch it is works good

    @IBOutlet weak var testTextField: UITextField!
    @IBOutlet weak var testSwitch: UISwitch!    

    let isOn = BehaviorRelay<Bool>(value: true)
    let text = BehaviorRelay<String>(value: "")
    let db = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        (testSwitch.rx.isOn <-> isOn).disposed(by: db)
        (testTextField.rx.textInput <-> text).disposed(by: db)
        
        isOn.subscribe(onNext: { (value) in
            print(value)
        }).disposed(by: db)
    }

**Comment by Davarg** [comment]
@Anavrin1990 Hello, I will fix this issue.

**Comment by Davarg** [comment]
@Anavrin1990 fixed

**Comment by Anavrin1990** [comment]
> @Anavrin1990 fixed

Thanks

**Comment by Anavrin1990** [comment]
Thanks
