### ISSUE TITLE
Update podspec to Swift 4.2

### ISSUE THREAD

**Issue by AmitaiB** [RxSwiftCommunity/RxBiBinding#25]
This warning makes my teeth itch. :)
![image](https://user-images.githubusercontent.com/11856134/52977271-ace24180-339a-11e9-87d5-c2ac97b449de.png)

Thanks, I _love_ what this little library does for my code's readability!

**Comment by Davarg** [comment]
@AmitaiB Hello, thank you for feedback, this is very cool when somebody likes your work 🙂
I will update pod
