### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by hk05** [RxSwiftCommunity/RxBiBinding#29]
I got really enthusiastic reading about RxBiBinding. Until I found out it is yet another ios-only project.  Would you please consider (also) making RxBiBinding available for macOS?

**Comment by Davarg** [comment]
@hk05 Hello, sorry for late response. I will implement support for macOS

**Comment by hk05** [comment]
Thanks you very much!!! Highly appreciated :-)

BR

Hans

**Comment by Davarg** [comment]
Added support for macOS
