### ISSUE TITLE
Carthage build problem for platform macOS

### ISSUE THREAD

**Issue by hk05** [RxSwiftCommunity/RxBiBinding#31]
Happy to see that RxBiBinding now supports macOS!!

I encounter a problem building for the macOS platform using carthage though:

> *** Skipped building RxBiBinding due to the error:
> Dependency "RxBiBinding" has no shared framework schemes for any of the platforms: Mac
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/RxSwiftCommunity/RxBiBinding/issues/new
> 

FWIW, I used carthage update --platform macOS with cartfile set to:

github "ReactiveX/RxSwift" ~> 5.0.1
github "RxSwiftCommunity/RxBiBinding.git"

Eager to start using RxBiBinding, I hope anyone can provide a fix for this. Thanks!

**Comment by Davarg** [comment]
@hk05 This might be my mistake. I will fix this ASAP

**Comment by Davarg** [comment]
@hk05 Fixed
