### ISSUE TITLE
Add Support to Rxswift 5.0.0

### ISSUE THREAD

**Issue by techmehra** [RxSwiftCommunity/RxBiBinding#34]

**Comment by Davarg** [comment]
@techmehra 
It's already added. What problem you have?

**Comment by onufrei** [comment]
@Davarg same issue, please find the error description below

> [!] CocoaPods could not find compatible versions for pod "RxSwift":
>   In Podfile:
>     RxBiBinding was resolved to 0.1.3, which depends on
>       RxSwift (~> 4.2.0)
> 
>     RxCocoa (~> 5) was resolved to 5.0.0, which depends on
>       RxSwift (~> 5)

**Comment by Davarg** [comment]
@onufrei 

1. Execute 'pod repo update'
2. Remove 'Pods' folder in your project
3. Execute 'pod install' in your project

**Comment by onufrei** [comment]
@Davarg still the same. Maybe 'cause of in the podspec was declared target version '~ 4.5', that not includes '5.0'?
```
[!] CocoaPods could not find compatible versions for pod "RxSwift":
  In Podfile:
    RxBiBinding was resolved to 0.2.1, which depends on
      RxSwift (~> 4.5)

    RxSwift (~> 5)
```

**Comment by Davarg** [comment]
@onufrei very strange. Okay, I will update Podspec soon.

**Comment by mudassar1122** [comment]
@Davarg this one issue in my code 
<img width="510" alt="Screen Shot 2022-06-03 at 3 05 52 PM" src="https://user-images.githubusercontent.com/84720123/171834128-0b4c12ed-1fae-45ac-9004-0fcae5114ea2.png">

**Comment by mudassar1122** [comment]
@Davarg please check this issue

**Comment by Davarg** [comment]
@mudassar1122 Hi there. As I see you are using very old library ```RxBluetoothKit 1.2.3``` which depends on ```RxSwift 2.0```.
```RxBiBinding``` doesn't support ```RxSwift 2.0```
Library ```RxBluetoothKit``` doesn't have support of ```RxSwift 6``` as I see here https://github.com/Polidea/RxBluetoothKit/blob/master/RxBluetoothKit.podspec

So maybe you should try update ```RxBluetoothKit``` library by yourself in separate repository or create reactive wrappers for bluetooth in your project

**Comment by mudassar1122** [comment]
<img width="1362" alt="Screen Shot 2022-06-03 at 8 17 11 PM" src="https://user-images.githubusercontent.com/84720123/171882937-190f4a03-9d57-457e-9d1e-233a3203fd41.png">
i am using these libraries : 

 pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
 pod 'Alamofire'
 pod 'ChromaColorPicker'
 pod 'iOSDFULibrary'
 pod 'ObjectMapper', '~> 3.5'
 pod 'OHHTTPStubs/Swift'
 pod 'RealmSwift', '~>10'
 pod 'RxAlamofire'
 pod 'RxDataSources', '~> 5.0'
 pod "RxRealm" 
 pod 'SwiftyUserDefaults', '~> 5.0'
 pod 'SwiftyBeaver'
 pod 'SwiftyAttributes'
 pod 'RxBluetoothKit'

**Comment by mudassar1122** [comment]
@Davarg please check this issue

**Comment by SJImobility** [comment]
<img width="1370" alt="image" src="https://github.com/RxSwiftCommunity/RxBiBinding/assets/80037350/a0995018-0ac7-4691-94de-edc4c4099084">
