### ISSUE TITLE
Add support for RxSwift 4.4 & Swift 4.2

### ISSUE THREAD

**Issue by d2vydov** [RxSwiftCommunity/RxBiBinding#35]

**Comment by d2vydov** [comment]
I've just created branch supports RxSwift 4.4 and Swift 4.2

`pod 'RxBiBinding', :git => 'https://github.com/dialogs/RxBiBinding.git', :tag => '0.2.3-rxswift4'`

**Comment by Davarg** [comment]
@d2vydov 
Hi, this is not a good idea to downgrade. Because it will be difficult to support normal branch and legacy. This is my opinion
