### ISSUE TITLE
Swift package manager resolution failing

### ISSUE THREAD

**Issue by jessemx109** [RxSwiftCommunity/RxBiBinding#39]
When trying to include RxBiBinding via swift package manager in Xcode 11 I am getting an error saying 

"The package dependency graph can not be resolved; unable find any available tag for the following requirements:"

<img width="734" alt="Screen Shot 2019-09-03 at 10 24 07 AM" src="https://user-images.githubusercontent.com/1411012/64194962-34723800-ce35-11e9-874a-b7e13af06f46.png">

**Comment by Davarg** [comment]
@jessemx109 Hi, I'm sorry, but only on weekend I can fix this issue. Feel free create PR if you have any solution.
