### ISSUE TITLE
Add support for Rxswift 6

### ISSUE THREAD

**Issue by jessemx109** [RxSwiftCommunity/RxBiBinding#41]
I am being blocked from upgrading my project to rxswift 6 by this dependency

**Comment by Davarg** [comment]
will be updated soon

**Comment by Davarg** [comment]
@jessemx109 Library updated

**Comment by jessemx109** [comment]
@Davarg when should I expect to see the new version in cocoapods?

**Comment by Davarg** [comment]
> @Davarg when should I expect to see the new version in cocoapods?

It's already there 
<img width="923" alt="pod_search" src="https://user-images.githubusercontent.com/7040205/105862604-07618f00-6001-11eb-8643-83c28ee6a0bc.png">
