### ISSUE TITLE
Update RxSwift & RxCocoa version

### ISSUE THREAD

**Issue by at-huytong** [RxSwiftCommunity/RxBiBinding#8]
Can you update podspec  so that it can be installed with newer version of RxSwift and RxCocoa ?
In my fork repo, I changed the version to 4.3.1 and it's working properly.

**Comment by Davarg** [comment]
Yes, I can. You can create pull request

**Comment by cukingpro** [comment]
I created a PR, please check it. Thank you
https://github.com/RxSwiftCommunity/RxBiBinding/pull/9

**Comment by Davarg** [comment]
Thanks to all
